### ISSUE TITLE
Setup Project Skeleton with VueJs, Pinia, and Quasar

### ISSUE THREAD

**Issue by DonNicoJs** [DonNicoJs/dog-trainer-companion#1]
**Description:**

The purpose of this issue is to set up the initial skeleton of our Dog Trainer Data Collection application. This setup will involve configuring the project with VueJs 3.0, integrating Pinia for state management, and using Quasar for the UI framework.

**Tasks:**

1. **Initialize VueJs Project:**
   - Create a new VueJs 3.0 project.
   - Ensure that the project is set up with the latest stable version of VueJs.

2. **Integrate Pinia:**
   - Install Pinia and set it up for state management.
   - Create a basic store as an example and demonstration of how Pinia will be used in the project.

3. **Add Quasar Framework:**
   - Install and configure Quasar in the project.
   - Ensure that Quasar components are compatible and work seamlessly with VueJs 3.0.

4. **Basic Routing Setup:**
   - Set up Vue Router for handling navigation within the app.
   - Include at least two routes (e.g., Home and About) for initial testing.

5. **Project Structure:**
   - Organize the project directory structure for components, views, stores, and other necessary folders.
   - Ensure a scalable and maintainable structure is in place.

6. **Linting and Formatting:**
   - Set up ESLint and Prettier for code linting and formatting to maintain code quality and consistency.

7. **Documentation:**
   - Document the setup process and the project structure.
   - Include instructions in the README for setting up the development environment.

**Acceptance Criteria:**

- The project runs without errors with VueJs, Pinia, and Quasar integrated.
- Basic navigation between different routes is functional.
- The code is properly linted and formatted.
- The README contains clear setup instructions.

**Additional Notes:**

- The setup should focus on scalability and best practices, considering the future integration of Firebase and other features.
- Ensure that all dependencies are compatible with each other.

**Comment by egentilucci** [comment]
I setup the initial project scaffolding using Quasar CLI (instead of using Quasar as a Vuejs plugin) in order to get all Quasar's functionalities. As indicated [here](https://quasar.dev/start/vue-cli-plugin) using Quasar as Vue Plugin has some limitations.
As for the project structure it's made by following Quasar's suggested [directory structure](https://quasar.dev/quasar-cli-webpack/directory-structure/).
